import { NextRequest, NextResponse } from 'next/server';
import { createServiceClient } from '@/lib/supabase/server';
import { logActivity } from '@/lib/api/activity';
import { validateWorkflowType } from '@/lib/api/validation';

// GET /api/tasks
export async function GET(request: NextRequest) {
    const supabase = await createServiceClient();
    const searchParams = request.nextUrl.searchParams;

    const projectId = searchParams.get('project_id');
    const planId = searchParams.get('plan_id');
    const phaseId = searchParams.get('phase_id');
    const statuses = searchParams.get('status')?.split(',') || [];
    const assigneeId = searchParams.get('assignee_id'); // maps to owner_id
    const priority = searchParams.get('priority');

    let query = supabase.from('task').select(`
    *,
    project:project_id(id, name),
    owner:owner_id(name)
  `);

    if (projectId) query = query.eq('project_id', projectId);
    if (planId) query = query.eq('plan_id', planId);
    if (phaseId) query = query.eq('phase_id', phaseId);
    if (statuses.length > 0) query = query.in('status', statuses as any);
    if (assigneeId) query = query.eq('owner_id', assigneeId);
    if (priority) query = query.eq('priority', priority as any);

    // Default sort
    query = query.order('created_at', { ascending: false });

    const { data, error } = await query;

    if (error) {
        return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ data });
}

// POST /api/tasks
export async function POST(request: NextRequest) {
    const supabase = await createServiceClient();
    const body = await request.json();

    if (!body.project_id || !body.title) {
        return NextResponse.json({ error: 'project_id and title are required' }, { status: 400 });
    }

    // 1. Fetch project to validate workflow rules
    const { data: project, error: projectError } = await supabase
        .from('project')
        .select('*')
        .eq('id', body.project_id)
        .single();

    if (projectError || !project) {
        return NextResponse.json({ error: 'Project not found' }, { status: 404 });
    }

    // 2. Validate workflow rules
    try {
        validateWorkflowType(project, body.plan_id, body.phase_id);
    } catch (err: any) {
        if (err.name === 'ValidationError') {
            return NextResponse.json({ error: err.message, details: err.details }, { status: 400 });
        }
        throw err;
    }

    // 3. Create task
    // display_id is generated by trigger
    const { data, error } = await supabase
        .from('task')
        .insert({
            project_id: body.project_id,
            plan_id: body.plan_id,
            phase_id: body.phase_id,
            title: body.title,
            description: body.description,
            status: 'pending',
            priority: body.priority,
            size: body.size,
            owner_id: body.owner_id,
            owner_type: body.owner_id ? 'human' : undefined, // Simplify for now
            deadline_at: body.deadline_at,
            source_id: body.source_id,
            data_origin: body.data_origin || 'native'
        } as any)
        .select()
        .single();

    if (error) {
        return NextResponse.json({ error: error.message }, { status: 500 });
    }

    await logActivity({
        entityType: 'task',
        entityId: data.id,
        actorType: 'human',
        actorId: body.owner_id, // If undefined, logActivity will fall back to 'jess' for now
        action: 'created',
        detail: { title: body.title }
    });

    return NextResponse.json({ data });
}
